name: Build wget

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  create:
    tags:
      - v*
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      matrix:
        ssl: [gnutls, openssl]
      fail-fast: false
    runs-on: ubuntu-24.04
    name: Build wget with ${{ matrix.ssl }}
    env:
      SSL_TYPE: ${{ matrix.ssl }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout project
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 mingw-w64-tools gcc
          sudo apt-get install -y make m4 pkg-config automake gettext gperf python3-venv 
          python3 -m venv myenv
          source myenv/bin/activate
          pip install setuptools
          pip install --upgrade setuptools
      - name: Build wget 64-bit with ${{ matrix.ssl }}
        run: |
          #chmod +x wget-${{ matrix.ssl }}.sh
          #./wget-${{ matrix.ssl }}.sh
          chmod +x wget-build.sh
          ./wget-build.sh
      - name: Archive ${{ matrix.ssl }}
        uses: actions/upload-artifact@v4
        with:
          name: wget-64bit-${{ matrix.ssl }}
          path: wget-${{ matrix.ssl }}/wget-${{ matrix.ssl }}-x64.exe
      - name: Create ${{ matrix.ssl }} Release  
        uses: ncipollo/release-action@v1 
        with:
          tag: 1.21.4
          allowUpdates: true
          artifacts: "wget-${{ matrix.ssl }}/wget-${{ matrix.ssl }}-x64.exe"
          bodyFile: "RELEASE.md"
          token: ${{ secrets.GITHUB_TOKEN }}
