name: wget

on:
  workflow_dispatch:
  create:
    tags:
      - v*

jobs:
  ubuntu:
    name:  build wget-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout project
      - name: Install prerequisites
        run: |
          sudo sed -i 's/http:\/\/azure\.archive\.ubuntu\.com\/ubuntu/http:\/\/archive\.ubuntu\.com\/ubuntu/' /etc/apt/apt-mirrors.txt
          sudo apt-get update
          sudo apt-get install -y mingw-w64 mingw-w64-tools gcc
          sudo apt-get install -y make m4 pkg-config automake gettext
      - name: Build wget 64-bit
        run: |
          x86_64-w64-mingw32-gcc --version
          ./build.sh
      - name: Archive gnutls
        uses: actions/upload-artifact@v4
        with:
          name: wget-1.21.4-64bit-GnuTLS
          path: wget-gnutls/wget-gnutls-x64.exe
      - name: Archive openssl
        uses: actions/upload-artifact@v4
        with:
          name: wget-1.21.4-64bit-OpenSSL
          path: wget-openssl/wget-openssl-x64.exe
      - name: Create Release  
        uses: ncipollo/release-action@v1 
        with:
          tag: 1.21.4
          allowUpdates: true
          artifacts: "wget-gnutls/wget-gnutls-x64.exe,wget-openssl/wget-openssl-x64.exe"
          bodyFile: "RELEASE.md"
          token: ${{ secrets.GITHUB_TOKEN }}
